# Partitionnez vos données - Le Bag of Words

## 1. Préliminaires

### 1.1 Contexte 
Ce TP est en lien avec l'activité [Partitionnez vos données](https://openclassrooms.com/fr/courses/4525281-realisez-une-analyse-exploratoire-de-donnees/5345241-tp-partitionnez-vos-donnees), de la partie 3 du cours  [Réalisez une analyse exploratoire de données](https://openclassrooms.com/fr/courses/4525281-realisez-une-analyse-exploratoire-de-donnees).

### 1.2 Imports

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import datasets

from sklearn.cluster import AgglomerativeClustering
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

from scipy.cluster.hierarchy import linkage,dendrogram,fcluster

### 1.3 Chargement des données

In [ ]:
# Chemin du repertoire data
data_dir = './data/'

# Chargement des données de bag of words
data = pd.read_csv(data_dir+'bag_of_words.csv')

# Affichage des 5 premières lignes
data.head()

,titre,aaaa,abandonner,abattement,abbr,abc,abondement,abonnement,abonner,abonnés,...,évoqué,évoquées,évoqués,évènement,évènements,événement,événements,êtres,œil,œuvre
0,Concevez des architectures Big Data,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0000,0.0,0.000469,0.000000,0.000000,0.000000
1,Apprenez à coder avec JavaScript,0.000000,0.0,0.0,0.0,0.000499,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0001,0.0,0.000000,0.000000,0.000000,0.000000
2,Concevez votre site web avec PHP et MySQL,0.000524,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0000,0.0,0.000000,0.000000,0.000087,0.000000
3,Réussir sa campagne d'e-mailing avec MailChimp,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.020408,0.020408,...,0.0,0.0,0.0,0.0,0.0000,0.0,0.000000,0.000000,0.000000,0.000000
4,Utilisez des modèles supervisés non linéaires,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0000,0.0,0.000000,0.000325,0.000000,0.000651

In [4]:
# Affichage des dimensions de data
data.shape

(105, 9344)

In [5]:
# Chargement des données sur les cours
courses_info = pd.read_csv(data_dir + "courses_info.csv")

# Affichage des 5 premières lignes
courses_info.head()

,title,charge-e-de-gestion-des-ressources-humaines,manager-rh,gestionnaire-de-paie,data-architect,developpeur-se-dapplication-python,developpeur-web-junior,community-manager,responsable-marketing-operationnel,developpeur-se-d-application-php-symfony,data-scientist,expert-e-en-strategie-marketing-et-communication,data-analyst,theme
0,Apprenez à gérer les conflits,True,True,True,False,False,False,False,False,False,False,False,False,RH
1,Réalisez des calculs distribués sur des donnée...,False,False,False,True,False,False,False,False,False,False,False,False,data
2,Managez une équipe au quotidien,False,True,False,False,False,False,False,False,False,False,False,False,RH
3,Gérez votre code avec Git et GitHub,False,False,False,False,True,True,False,False,False,False,False,False,dev
4,Lancez une campagne de publicité avec Google A...,False,False,False,False,False,False,True,True,False,False,False,False,marketing

In [6]:
courses_info.shape

(112, 14)

## 2 Preparation des données

### 2.1 Merge
On va fusionner les deux dataframes dans le dataframe data

In [7]:
# Choix des colonnes de courses_info
cols=["title","theme"]

# Enregistrement dans un dataframe temporaire
temp = courses_info[cols]
temp.head()

                                               title      theme
0                      Apprenez à gérer les conflits         RH
1  Réalisez des calculs distribués sur des donnée...       data
2                    Managez une équipe au quotidien         RH
3                Gérez votre code avec Git et GitHub        dev
4  Lancez une campagne de publicité avec Google A...  marketing